### ISSUE TITLE
Not working with XCode 15.3 and Command Line Tools 15.3 (15E204a)

### ISSUE THREAD

**Issue by Luckfried** [jasonacox/Build-OpenSSL-cURL#67]
![image](https://github.com/jasonacox/Build-OpenSSL-cURL/assets/6279698/497cbf0e-d0a4-4aeb-9b45-6355ac5b4954)

**Comment by jasonacox** [comment]
Thanks @Luckfried  - we likely need to upgrade the tvOS version. Are the other targets (iOS, MacOS) building correctly?

**Comment by jasonacox** [comment]
Update. XCode 15.2 works with the following library version.

```bash
OPENSSL="3.0.12"        # https://www.openssl.org/source/ 
LIBCURL="8.5.0"         # https://curl.haxx.se/download.html
NGHTTP2="1.58.0"        # https://nghttp2.org/
```

I'm upgrafing to XCode 15.3 to see what causes the break. I suspect we may need to change the min SDK versions.

**Comment by jasonacox** [comment]
The error that is generated with XCode 15.3:

```
crypto/ui/ui_openssl.c:273:17: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
static volatile intr_signal;
~~~~~~~~~~~~~~~ ^
int
1 error generated.
```

**Comment by jasonacox** [comment]
Fix required adding `int` to declaration. I don't know why it wouldn't be there already and why it only impacts tvOS.  A quick `sed` added to tvOS build:

```bash
# Starting with XCode 15.3
LANG=C sed -i -- 's/static volatile intr_signal/static volatile int intr_signal;/' "./crypto/ui/ui_openssl.c"
```

I discovered a second issue with latest cURL library (8.6.0) that now requires the libpsl library which is not available by default. We have not included this in prior version so I'm using the `--without-libpsl` for now while I figure out an easy way to get a static cross-compile of the library.

Now working with latest:
curl/8.6.0 libcurl/8.6.0 OpenSSL/3.0.13 zlib/1.2.12 nghttp2/1.60.0
