### ISSUE TITLE
Build error with OpenSSL 1.1.1q

### ISSUE THREAD

**Issue by rbright55** [jasonacox/Build-OpenSSL-cURL#59]
Build error occurs when trying to build with OpenSSL 1.1.1q. The error occurs when it is attempting to build for iOS.

**Comment by jasonacox** [comment]
Hi @rbright55 !  Thanks for opening this!  

I'll do some investigation.  If anyone else has discovered the cause for the build failure, please feel free to update here (or submit a PR if you figure it out! :).

**Comment by jasonacox** [comment]
Posting error that is causing this to break:

```
cc  -Iinclude -arch x86_64 -Os -mmacosx-version-min=11.6.8 -arch x86_64  -D_REENTRANT -DNDEBUG  -MMD -MF test/versions.d.tmp -MT test/versions.o -c -o test/versions.o test/versions.c
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 error generated.
make[1]: *** [test/v3ext.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

**Comment by jasonacox** [comment]
@rbright55 This is an open issue on OpenSSL: https://github.com/openssl/openssl/issues/18720

It looks like a fix has been pushed and should show up in the next version.  We can keep this open until a fixed version is released.  I am also going to add `set -e` to the `build.sh` script as it is difficult to spot / troubleshoot these errors when build.sh just plows on ahead.

**Comment by jasonacox** [comment]
Great explaination by @tom-cosgrove-arm in https://github.com/openssl/openssl/issues/18720#issuecomment-1210284214
